name: Deploy website
on:
  push:
    branches:
      - new
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm install
      - name: Lint code
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm run lint
      - name: Test code
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm install
      - name: Build website
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
         name: dist-dir
         path: |
          dist
          package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
