name: Deploy website
on:
  push:
    branches:
      - new
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm install
      - name: Lint code
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm run lint
      - name: Test code
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm install
      - name: Build website
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        working-directory: "course-section-5/artifacts-and-outputs/01 Starting Project"
        with:
         name: dist-dir
         path: |
          "course-section-5/artifacts-and-outputs/01 Starting Project/dist"
          "course-section-5/artifacts-and-outputs/01 Starting Project/package.json"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
