name: Website Deployment
on:
  push:
    branches:
      - new
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.output.cache-hit != true
        working-directory: "course-section-6/workflow-job-execution/01 Starting Project"
        run: npm install
      - name: Lint code
        working-directory: "course-section-6/workflow-job-execution/01 Starting Project"
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: "course-section-6/workflow-job-execution/01 Starting Project"
        run: npm install
      - name: Test code
        id: one
        working-directory: "course-section-6/workflow-job-execution/01 Starting Project"
        run: npm run test
      - name: Upload test report
        if: failure() && ${{ steps.one.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: "course-section-6/workflow-job-execution/01 Starting Project"
        run: npm install
      - name: Build website
        id: build-website
        working-directory: "course-section-6/workflow-job-execution/01 Starting Project"
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: "course-section-6/workflow-job-execution/01 Starting Project/dist"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  failure-message:
   runs-on: ubuntu-latest
   needs: [deploy,build,test,lint]
   if: failure()
   steps:
    - name: Job Failure Message
      run: echo "Something Went Wrong!"
   
