name: Re-using Workflows
on: 
 workflow_call:
  inputs:
   artifact-name:
    description: The Name Of Deployable Artifact Files
    required: false
    default: dist-dir
    type: string
jobs:
 demo:
  runs-on: ubuntu-latest
  steps:
   - name: Demo Message
     run: echo "Reusable Workflow Demo"
   - name: Downloading Artifacts
     uses: actions/download-artifact@v4
     with:
      name: ${{inputs.artifact-name}}
   - name: List Files Post Artifacts Download
     run: ls