name: Environment Secrets And Environment Variables
on: [push,workflow_dispatch]
jobs:
 test_deployment_server:
  runs-on: ubuntu-latest
  environment: drf-demo-project
  env:
   DSK: ${{secrets.DSK}}
  steps:
   - name: Checkout The Repository
     uses: actions/checkout@v5
   - name: Setup Python
     uses: actions/setup-python@v5
     with:
      python-version: '3.13.7'
   - name: Download Dependencies 
     working-directory: "course-section-4/envvars-secrets"
     run: pip install -r requirements.txt
   - name: Make Relevant Migrations
     working-directory: "course-section-4/envvars-secrets"
   - name: Test Development Server
     working-directory: "course-section-4/envvars-secrets"
     run: python manage.py runserver
