name: Testing React Project
on: [push,workflow_dispatch]
jobs:
 testing:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
   - name: Install NodeJS
     uses: actions/setup-node@v3
     with:
      node-version: 18
   - name: Install Dependencies
     working-directory: "course-section-2/github-actions-basic/02 Starting Project"
     run: npm install
   - name: Run Tests
     working-directory: "course-section-2/github-actions-basic/02 Starting Project"
     run: npm test    
 deployment:
  needs: testing
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
   - name: Install NodeJS
     uses: actions/setup-node@v3
     with:
      node-version: 18
   - name: Install Dependencies
     working-directory: "course-section-2/github-actions-basic/02 Starting Project"
     run: npm install
   - name: Build And Run
     working-directory: "course-section-2/github-actions-basic/02 Starting Project"
     run: npm run build   